"""add_tsvector_to_chunks

Revision ID: 2b9424bc7633
Revises: 2ca9f90087bc
Create Date: 2026-01-27 03:13:50.793489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b9424bc7633'
down_revision: Union[str, Sequence[str], None] = '2ca9f90087bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('content_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=True))
    op.create_index('ix_chunks_content_vector', 'chunks', ['content_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_content_vector', table_name='chunks', postgresql_using='gin')
    op.drop_column('chunks', 'content_vector')
    # ### end Alembic commands ###
