"""add_project_id_to_chunks

Revision ID: a6b32718b314
Revises: 2b9424bc7633
Create Date: 2026-01-27 03:21:58.632340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b32718b314'
down_revision: Union[str, Sequence[str], None] = '2b9424bc7633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add as nullable
    op.add_column('chunks', sa.Column('project_id', sa.Uuid(), nullable=True))
    
    # 2. Data Migration: Populate project_id from documents table
    op.execute(
        "UPDATE chunks SET project_id = documents.project_id FROM documents WHERE chunks.document_id = documents.id"
    )
    
    # 3. Set to NOT NULL
    op.alter_column('chunks', 'project_id', nullable=False)
    
    op.create_index(op.f('ix_chunks_project_id'), 'chunks', ['project_id'], unique=False)
    op.create_foreign_key(None, 'chunks', 'projects', ['project_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_index(op.f('ix_chunks_project_id'), table_name='chunks')
    op.drop_column('chunks', 'project_id')
    # ### end Alembic commands ###
